# Numpy Module

In [3]:
import numpy as np 


### create a one dimensional array using np.array to 

In [3]:
array = np.array([ 1,2,10,5.7])
print(array) 

[ 1.   2.  10.   5.7]


### create a two dimensional array using np.array 

In [4]:
array2 = np.array([[10, 6.4], [14, 7], [12, 8]])
print(array2)


[[10.   6.4]
 [14.   7. ]
 [12.   8. ]]


### arrays with sequences of numbers (print number from A to B-1)

In [6]:
numbers = np.arange(5, 12)
print(numbers)

[ 5  6  7  8  9 10 11]


###   return random numbers between low and high ( size have dimensional value number )

In [7]:
random_numbers = np.random.randint(low=70, high=101, size=(6))
print(random_number)

[81 90 98 87 92 81]


### size can have two or more value  size ( 3 , 4 ) => size ( row , column )

In [8]:
random_numbers2 = np.random.randint(low=70, high=101, size=(3,4))
print(random_numbers2)

[[ 84  87  82  94]
 [ 97  73  78  90]
 [100  87  89  87]]


### return random number between 0 and 1,  ( 4 is number of numbers  )
####  np.random.random([4])       => return one dimensional array have 4 column
####  np.random.random([4 , 2 ]) => return two dimensional array have 4 rows and 2 columns

In [18]:
random_floats = np.random.random([4])
print(random_floats) 


[0.88323989 0.4883455  0.74099882 0.93755819]


### return random float numbers between 0+x and 1+x ( 4 is number of numbers  )
### 2.0 is x value
#### array values between 2 and 3

In [21]:
random_floats_2 =  np.random.random([4]) + 2.0
print(random_floats_2)

[2.55817945 2.29588088 2.08795404 2.01278876]


### return random float numbers between 0*x and 1*x ( 4 is number of number  )
### 3 is x value
#### array values between 0 and 3

In [20]:
random_floats_3 =  np.random.random([4]) * 3
print(random_floats_3)

[0.97270499 0.0718615  2.55488195 1.72352001]


## Task 1


#### Your goal is to create a simple dataset consisting of a single feature and a label as follows:
#### Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named feature.
#### Assign 15 values to a NumPy array named label such that:
####   label = (3)(feature) + 4
#### For example, the first value for label should be:
####  label = (3)(6) + 4 = 22

In [47]:
feature = np.arange(6, 21)
label = 3*feature +4
print (f'feature is: {feature}')
print (f'label is:   {label}  ')

feature is: [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
label is:   [22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]  


## Task 2

#### To make your dataset a little more realistic, insert a little random noise into each element of the label array you already created. To be more precise, modify each value assigned to label by adding a different random floating-point value between -2 and +2.  
#### Don't rely on broadcasting. Instead, create a noise array having the same dimension as label.


In [50]:
noise = ( np.random.random([len(label)]) *4 )- 2
print(noise)
print('-----------------------------')
label = label + noise
print(label)

[ 1.35762941 -0.03340407 -0.42080261 -0.48468673 -0.83729129 -1.55384481
 -0.27894637  0.20160704 -0.25286188  1.89302478  1.59927541 -1.73653766
 -1.73554847  0.08516247  0.02848013]
-----------------------------
[23.41898591 24.79752771 27.75144974 30.44475729 36.53135685 35.52029534
 37.54156563 45.04899489 45.06435538 49.64003394 50.2888469  55.05512298
 56.41477074 64.27548023 62.38316327]


# Finish